echo "GOOGLE_PLAY_PUBLISHING=true" > $CM_ENV

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -63,25 +63,22 @@ workflows:
       scripts:
         - name: Push git tags
           script: | 
-            set -e # exit on first failed command
-            set -x # print all executed commands to the log
+            # set -e # exit on first failed command
+            # set -x # print all executed commands to the log
 
-            new_version=v1.0.$BUILD_NUMBER
-            git tag $new_version
-            git push "https://dtrdic:$GITHUB_TOKEN@github.com/ionicTestApp4.git" --tags
+            # new_version=v1.0.$BUILD_NUMBER
+            # git tag $new_version
+            # git push "https://dtrdic:$GITHUB_TOKEN@github.com/ionicTestApp4.git" --tags
 
-            if [ "$CM_BUILD_STEP_STATUS" = "success" ]
-            then
-              new_version=v1.0.$BUILD_NUMBER
-              git tag $new_version
-              git push "https://dtrdic:$GITHUB_APP_PASS@github.com/ionicTestApp4.git" --tags
-            fi
+            # if [ "$CM_BUILD_STEP_STATUS" = "success" ]
+            # then
+            #   new_version=v1.0.$BUILD_NUMBER
+            #   git tag $new_version
+            #   git push "https://dtrdic:$GITHUB_APP_PASS@github.com/ionicTestApp4.git" --tags
+            # fi
 
-          #  git tag -a "googlestore4" -m "Published to google store"
-          #     git push origin main --tags
-          #  if [ -f ~/SUCCESS ]; then
-          #    # COMMIT_HASH=$(git rev-parse HEAD) 
-
-          #     git tag -a "googlestore3" -m "Published to google store"
-          #     git push origin main --tags
-          #   fi
+       
+            if [ -f ~/SUCCESS ]; then
+              echo "GOOGLE_PLAY_PUBLISHING=true" > $CM_ENV
+              fi
+              echo "the value of cm_env now is:" $CM_ENV
