x-access-token

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -64,22 +64,14 @@ workflows:
       scripts:
         - name: Push git tags
           script: | 
-            # set -e # exit on first failed command
-            # set -x # print all executed commands to the log
+            set -e # exit on first failed command
+            set -x # print all executed commands to the log
 
-            # new_version=v1.0.$BUILD_NUMBER
-            # git tag $new_version
-            # git push "https://dtrdic:$GITHUB_TOKEN@github.com/ionicTestApp4.git" --tags
+            if [ "$CM_BUILD_STEP_STATUS" = "success" ]
+            then
+              new_version=v1.0.$BUILD_NUMBER
+              git tag $new_version
+            git push "https://x-access-token:$GITHUB_TOKEN@github.com/ionicTestApp4.git" --tags
+            fi
 
-            # if [ "$CM_BUILD_STEP_STATUS" = "success" ]
-            # then
-            #   new_version=v1.0.$BUILD_NUMBER
-            #   git tag $new_version
-            # git push "https://dtrdic:$GITHUB_TOKEN@github.com/ionicTestApp4.git" --tags
-            # fi
-
-            echo "variable value at start is" $CM_ENV
-            echo "GOOGLE_PLAY_PUBLISHING=true" > $CM_ENV
-            echo "the value of cm_env now is:" $CM_ENV
-            # if [ -f ~/SUCCESS ]; then
-            # fi
+ 
